CXX=g++
TARGETS=hw2

# MinGW
ifeq "$(OS)" "Windows_NT"
CXXFLAGS=-O3 -Wall -pedantic -std=c++11
LIBS=-lglut32cu -lglu32 -lopengl32
CLEAN=del *.exe *.o *.a
else
# OSX
ifeq "$(shell uname)" "Darwin"
CXXFLAGS=-O3 -Wall -Wno-deprecated-declarations -pedantic -std=c++11
LIBS=-framework GLUT -framework OpenGL
# Linux/Unix/Solaris
else
CXXFLAGS=-O3 -Wall -pedantic -std=c++11
LIBS=-lglut -lGLU -lGL -lm
endif
#  OSX/Linux/Unix/Solaris
CLEAN=rm -f $(TARGETS) *.o *.a
endif

#  Compile and link
hw2:hw2.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)

#  Clean
clean:
	$(CLEAN)
